# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "execjs", "2.7.0"

gem "minitest", "~>5.10", :group => [:development, :test]
gem "hoe-yard", ">=0.1.3", :group => [:development, :test]
gem "hoe-bundler", ">=1.2", :group => [:development, :test]
gem "hoe-gemspec", ">=1.0", :group => [:development, :test]
gem "hoe-git", ">=1.6", :group => [:development, :test]
gem "yard", "~>0.8", :group => [:development, :test]
gem "redcarpet", "~>3.3", :group => [:development, :test]
gem "hoe", "~>3.16", :group => [:development, :test]

# vim: syntax=ruby
